In [1]:
from scipy import *
from matplotlib.pyplot import *
from scipy.linalg import *
from numpy.linalg import *
import scipy.sparse as sparse
import numpy as np
import pandas as pd
from scipy.sparse.linalg import splu
from timeit import default_timer as timer
import matplotlib.pyplot as plt

In [2]:
def lufact(A):
	"""
	lufact(A)

	Compute the LU factorization of square matrix A, returning the factors.
	"""
	n = A.shape[0]
	L = np.eye(n)
	U = A.copy()

	# Gaussian elimination
	for j in range(n-1):
		for i in range(j+1,n):
			L[i,j] = U[i,j] / U[j,j]   # row multiplier
			U[i,j:] = U[i,j:] - L[i,j]*U[j,j:]
	return L, np.triu(U)

def forwardsub(L,b):
	"""
 	forwardsub(L,b)

	Solve the lower-triangular linear system with matrix L and right-hand side
	vector b.
	"""
	n = len(b)
	x = np.zeros(n)
	for i in range(n):
		s = L[i,:i] @ x[:i]
		x[i] = ( b[i] - s ) / L[i,i]
	return x


def backsub(U,b):
	"""
	backsub(U,b)

	Solve the upper-triangular linear system with matrix U and right-hand side
	vector b.
	"""
	n = len(b)
	x = np.zeros(n)
	for i in range(n-1,-1,-1):
		s = U[i,i+1:] @ x[i+1:]
		x[i] = ( b[i] - s ) / U[i,i]
	return x

# T2

In [3]:
A = np.array([[1, 0, -1], [0, 4, 5], [-1, 5, 10]])
B = np.array([[1, 0, 1], [0, 4, 5], [-1, 5, 10]])
C = np.array([[1, 0, 1], [0, 4, 5], [1, 5, 1]])

In [4]:
cholesky(A)

array([[ 1.       ,  0.       ,  0.       ],
       [ 0.       ,  2.       ,  0.       ],
       [-1.       ,  2.5      ,  1.6583124]])

In [5]:
cholesky(B)

array([[ 1.       ,  0.       ,  0.       ],
       [ 0.       ,  2.       ,  0.       ],
       [-1.       ,  2.5      ,  1.6583124]])

In [6]:
cholesky(C)

LinAlgError: Matrix is not positive definite

# T4

In [7]:
def lufact(A):
	"""
	lufact(A)

	Compute the LU factorization of square matrix A, returning the factors.
	"""
	n = A.shape[0]
	L = np.eye(n)
	U = A.copy()

	# Gaussian elimination
	for j in range(n-1):
		for i in range(j+1,n):
			L[i,j] = U[i,j] / U[j,j]   # row multiplier
			U[i,j:] = U[i,j:] - L[i,j]*U[j,j:]
	return L, np.triu(U)

def luband(A, upper, lower):
	n = A.shape[0]
	L = np.eye(n)
	U = A.copy()

	# Gaussian elimination
	for j in range(n-1):
		for i in range(j+1,min(j + lower + 1, n)):
			L[i,j] = U[i,j] / U[j,j]   # row multiplier
			for k in range(j, min(j + upper + 1, n)):
				U[i,k] = U[i,k] - L[i,j]*U[j,k]
	return L, np.triu(U)

In [ ]:
lower = 2
upper = 1

def get_matrix_A(n):
    A = np.zeros([n, n])
    for i in range(n):
        for j in range(n):
            if i-j >= -1 and i-j <= 2:
                A[i, j] = 1.0/(i+1+j+1)
    return A

In [34]:
n_values = [40*k for k in range(1, 21)]
print("    N    LU TIME    LU BAND TIME")
for n in n_values:
    start = timer()
    L, U = lufact(A)
    t1 = timer() - start

    start = timer()
    L, U = luband(A, upper=1, lower=2)
    t2 = timer() - start
  
    print(f"{n:5}   {t1:10.3e} {t2:10.3e}")


    N    LU TIME    LU BAND TIME
   40    1.297e-04  4.120e-05
   80    6.400e-05  3.810e-05
  120    6.050e-05  3.600e-05
  160    6.010e-05  2.235e-04
  200    1.078e-04  3.930e-05
  240    6.060e-05  3.520e-05
  280    6.080e-05  3.350e-05
  320    5.890e-05  3.310e-05
  360    5.910e-05  3.440e-05
  400    5.900e-05  3.180e-05
  440    5.820e-05  3.200e-05
  480    5.860e-05  3.280e-05
  520    5.910e-05  3.200e-05
  560    5.860e-05  3.170e-05
  600    5.880e-05  3.180e-05
  640    5.840e-05  3.140e-05
  680    5.870e-05  3.300e-05
  720    5.850e-05  3.130e-05
  760    5.820e-05  3.340e-05
  800    6.350e-05  3.180e-05


[[ 1.          0.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.          0.        ]
 [ 0.5         1.2         1.          0.          0.        ]
 [ 0.          6.         14.41558442  1.          0.        ]
 [ 0.          0.         -1.70454545 -0.18332467  1.        ]]
[[ 0.5         0.33333333  0.          0.          0.        ]
 [ 0.          0.02777778  0.2         0.          0.        ]
 [ 0.          0.         -0.07333333  0.14285714  0.        ]
 [ 0.          0.          0.         -1.9343692   0.11111111]
 [ 0.          0.          0.          0.          0.12036941]]
