### 2

In [1]:
import numpy as np

# define the matrices and vectors
A = np.array([
    [2, 1, 1, 0],
    [0, -1, 4, 1],
    [2, 2, 0, -2],
    [1, 3, -1, 5]
])
B = np.array([
    [3, -1, 0, 2],
    [7, 1, 0, 2]
])
u = np.array([[2], [-1], [3], [1]])
v = np.array([[np.pi], [np.e]])  # \pi and e can be derectly used in numpy

In python

- `@` is used to represent matrix multiplication, and 
- `*` is used to represent element-wise multiplication.

We use @ to represent matrix multiplication.

In [2]:
# (a) AB
AB = A @ B  # it is invalid

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [3]:
# (b) BA
BA = np.dot(B, A)
print("(b) BA = \n", BA)

(b) BA = 
 [[ 8 10 -3  9]
 [16 12  9 11]]


In [4]:
# (c) v^T B
v_T_B = np.dot(v.T, B)  # v.T is the transpose of v
print("(c) v^T B = \n", v_T_B)

(c) v^T B = 
 [[28.45275076 -0.42331083  0.         11.71974896]]


In [5]:
# (d) Bu
Bu = np.dot(B, u)
print("(d) Bu = \n", Bu)

(d) Bu = 
 [[ 9]
 [15]]


In [6]:
# (e) [u Au A^2u A^3u]
Au = A @ u
A2u = A @ Au
A3u = A @ A2u
result_e = np.concatenate([u, Au, A2u, A3u], axis=1)
print("(e) $[u Au A^2u A^3u]$ = \n", result_e)

(e) $[u Au A^2u A^3u]$ = 
 [[  2   6  26  77]
 [ -1  14 -13 218]
 [  3   0  38 -80]
 [  1   1  53 214]]


### 3

In [7]:
import numpy as np

u = np.array([1, 3, 5, 7, 9, 11]).reshape(-1, 1)
v = np.array([-60, -50, -40, -30, -20, -10]).reshape(-1, 1)

# inner product
inner_uv = np.dot(u.T, v)[0, 0]
inner_vu = np.dot(v.T, u)[0, 0]

# outer product
outer_uv = np.dot(u, v.T)
outer_vu = np.dot(v, u.T)

print("inner product u^T v:", inner_uv)
print("inner product v^T u:", inner_vu)
print("outer product u v^T:\n", outer_uv)
print("outer product v u^T:\n", outer_vu)

# you may find that the outer product u v^T is transpose of v u^T

inner product u^T v: -910
inner product v^T u: -910
outer product u v^T:
 [[ -60  -50  -40  -30  -20  -10]
 [-180 -150 -120  -90  -60  -30]
 [-300 -250 -200 -150 -100  -50]
 [-420 -350 -280 -210 -140  -70]
 [-540 -450 -360 -270 -180  -90]
 [-660 -550 -440 -330 -220 -110]]
outer product v u^T:
 [[ -60 -180 -300 -420 -540 -660]
 [ -50 -150 -250 -350 -450 -550]
 [ -40 -120 -200 -280 -360 -440]
 [ -30  -90 -150 -210 -270 -330]
 [ -20  -60 -100 -140 -180 -220]
 [ -10  -30  -50  -70  -90 -110]]


### 4

In [8]:
import numpy as np

# generate random matrix A and B
A = np.random.rand(3, 4)
B = np.random.rand(4, 2)

AB = A @ B
AB_T = AB.T

B_T = B.T
A_T = A.T
B_T_A_T = np.dot(B_T, A_T)

print("(AB)^T = \n", AB_T)
print("B^T A^T = \n", B_T_A_T)

(AB)^T = 
 [[0.84653577 0.51943991 0.51903588]
 [0.64760089 0.57347854 0.6099831 ]]
B^T A^T = 
 [[0.84653577 0.51943991 0.51903588]
 [0.64760089 0.57347854 0.6099831 ]]
